### ISSUE TITLE
not working with php8.0 stable

### ISSUE THREAD

**Issue by francogp** [icamys/php-sitemap-generator#20]
your dependencies does not support php 8.0

```
   Problem 1
     - Root composer.json requires astrotomic/php-open-graph ^0.5.0 -> satisfiable by astrotomic/php-open-graph[0.5.0].
     - astrotomic/php-open-graph 0.5.0 requires php ^7.1 -> your php version (8.0.0) does not satisfy that requirement.
   Problem 2
     - icamys/php-sitemap-generator[2.0.0, ..., 2.0.3] require php ^7.2 -> your php version (8.0.0) does not satisfy that requirement.
     - Root composer.json requires icamys/php-sitemap-generator ^2 -> satisfiable by icamys/php-sitemap-generator[2.0.0, 2.0.1, 2.0.3].
```

**Comment by icamys** [comment]
@francogp Thanks for sharing! I'll take a look at it on holidays.

**Comment by icamys** [comment]
@francogp Updated. Please see version [3.0.0](https://github.com/icamys/php-sitemap-generator/releases/tag/3.0.0).

**Comment by francogp** [comment]
does toggleGZipFileCreation disappeared?

**Comment by icamys** [comment]
@francogp Sorry to hear that you couldn't use the package.

Regarding (1). It works fine on PHP8. I've just cloned the repository and copied the example from the readme:

![image](https://user-images.githubusercontent.com/6891299/103571130-09896f80-4ed3-11eb-8561-f739a61b4d05.png)

Also, the tests [are passing on php8](https://travis-ci.org/github/icamys/php-sitemap-generator). If you could share some information about the error you get, not just "cannot use", I would be glad to help you with that.

Regarding (2). Yes, it is intended. The reason why the `enableCompression` does not generate both compressed and uncompressed sitemap files, except the case when you have a sitemap index file because you will submit to the search engines only one file. There's absolutely no need to have both files.

**Comment by icamys** [comment]
@francogp I suppose you are trying to use old versions of the generator, like `^2.*` or `^3.*`. In that case, the package should not work, right as you said. The current stable version is `4.3.0` and it works fine. Try to upgrade to this package version. As there were several major version changes, the interface has changed and is backward incompatible.

**Comment by francogp** [comment]
now it seems to be updated. When I looked before, the README.md looks old. Problem solved.
