### ISSUE TITLE
Mulitlanguage sitemap

### ISSUE THREAD

**Issue by alenamartinkova** [icamys/php-sitemap-generator#40]
Hello, 

I am using your sitemap generator for project I am working on and I have an issue with alternate URLs. 

When I create sitemap with alternate URLs, in browser it shows only the first one, and the alternate is visible only in code/inspector.

Is there something I can do about that?

Attached screenshot of browser.

Thank you,
Alena Martinkova

<img width="1422" alt="Screenshot 2022-07-14 at 13 39 35" src="https://user-images.githubusercontent.com/55541043/178974770-9f24395f-b971-460a-beb7-6a4cc2bad746.png">

**Comment by icamys** [comment]
Hi @alenamartinkova. The way browsers display XML content depends on their implementation and the best way to read XML files is either to use code inspector or to just download it to your local machine and open it with any text editor. Since the issue does not have anything with the library, I'll close this issue.
